name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  auto-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node env
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: yarn

      - name: Build (upgrade.voken.io)
        run: yarn build

      - name: CNAME (upgrade.voken.io)
        run: echo "upgrade.voken.io" > ./dist/CNAME

      - name: Deploy (upgrade.voken.io)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: voken1000g/upgrade.voken.io
          commit-message: "${{ github.repository }}@${{ github.sha }}"
          branch: main
          folder: dist

      - name: Clear
        run: rm -rf ./dist

      - name: Build (voken1000g.github.io/upgrade)
        run: yarn build-repo

      - name: Deploy (voken1000g.github.io/upgrade)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          commit-message: "@${{ github.sha }}"
          branch: gh-pages
          folder: dist
